"use client";

import { useRun } from "@/components/run/RunProvider";
import { RunHeader } from "@/components/run/RunHeader";
import { api } from "@/lib/api";

export function ReportScreen() {
  const { workspace } = useRun();
  if (!workspace) return <p className="empty">Loading report…</p>;
  const report = workspace.report;
  async function copyMarkdown() {
    if (!report) return;
    await navigator.clipboard.writeText(report.body_markdown);
  }
  return (
    <div>
      <RunHeader workspace={workspace} />
      <div className="grid cols-2">
        <article className="card">
          <div className="row" style={{ justifyContent: "space-between" }}>
            <h2 className="wrap-text">{report?.title ?? "Research report"}</h2>
            {report ? (
              <div className="row">
                <button className="btn" onClick={() => void copyMarkdown()}>Copy</button>
                <a className="btn" href={api.exportUrl(workspace.run_id, "markdown")}>Export Markdown</a>
                <a className="btn" href={api.exportUrl(workspace.run_id, "pdf")}>Export PDF</a>
                <a className="btn" href={api.exportUrl(workspace.run_id, "json")}>Export JSON</a>
              </div>
            ) : null}
          </div>
          {report ? (
            <pre className="wrap-text">{report.body_markdown}</pre>
          ) : (
            <p className="empty">The report appears when synthesis completes. Monitoring stays on the live research view until then.</p>
          )}
        </article>
        <aside className="drawer">
          <h2>Report information</h2>
          <p>Generated by: Synthesis Agent / Report Engine</p>
          <p>Model: {workspace.llm_model}</p>
          <p>Claims: {workspace.counts.claims}</p>
          <p>Sources: {workspace.counts.sources}</p>
          <p>Workers: {workspace.workers.length}</p>
          <p className="muted">Citations in the markdown body resolve through evidence IDs on the Claims screen. No raw HTML is injected.</p>
        </aside>
      </div>
    </div>
  );
}
