export const FIXTURE_RUN_ID = "11111111-1111-4111-8111-111111111111";

export const overviewFixture = {
  active: {
    id: FIXTURE_RUN_ID,
    goal: "Compare NMC and LFP battery chemistries",
    status: "running",
    llm_provider: "google",
    llm_model: "gemini-3.7-flash",
    termination_reason: null,
    created_at: "2026-08-21T10:00:00.000Z",
    updated_at: "2026-08-21T10:02:00.000Z",
    started_at: "2026-08-21T10:00:10.000Z",
    completed_at: null,
    total_tokens: 1200,
    cost_usd: 0.04,
    cost_status: "estimated",
    source_count: 3,
    evidence_count: 2,
    claim_count: 2,
    task_count: 3,
    completed_task_count: 1,
  },
  recent: [
    {
      id: FIXTURE_RUN_ID,
      goal: "Compare NMC and LFP battery chemistries",
      status: "running",
      llm_provider: "google",
      llm_model: "gemini-3.7-flash",
      termination_reason: null,
      created_at: "2026-08-21T10:00:00.000Z",
      updated_at: "2026-08-21T10:02:00.000Z",
      started_at: "2026-08-21T10:00:10.000Z",
      completed_at: null,
      total_tokens: 1200,
      cost_usd: 0.04,
      cost_status: "estimated",
      source_count: 3,
      evidence_count: 2,
      claim_count: 2,
      task_count: 3,
      completed_task_count: 1,
    },
  ],
  totals: {
    runs: 4,
    sources: 12,
    evidence: 8,
    claims: 6,
    known_cost_usd: 0.12,
    cost_status: "estimated",
    avg_completion_seconds: 180,
  },
  identity: { label: "Local workspace", role: "Operator", mode: "local" },
  langsmith: { connected: true, project: "deepscout-dev", region: "EU", tracing: true },
  providers: { google: { configured: true, model: "gemini-3.7-flash" } },
};

export const workspaceFixture = {
  run_id: FIXTURE_RUN_ID,
  status: "running",
  goal: "Compare NMC and LFP battery chemistries",
  termination_reason: null,
  llm_provider: "google",
  llm_model: "gemini-3.7-flash",
  research_mode: "standard",
  output_language: "en",
  created_at: "2026-08-21T10:00:00.000Z",
  updated_at: "2026-08-21T10:02:00.000Z",
  started_at: "2026-08-21T10:00:10.000Z",
  completed_at: null,
  budget: {
    max_iterations: 3,
    max_sources: 20,
    max_tool_calls: 40,
    max_total_tokens: 80000,
    max_cost_usd: 2,
    concurrency_limit: 3,
  },
  usage: {
    input_tokens: 800,
    output_tokens: 400,
    cached_input_tokens: 0,
    reasoning_tokens: 0,
    total_tokens: 1200,
    cost_usd: 0.04,
    usage_status: "provider_reported",
    cost_status: "estimated",
    pricing_version: "2026-08-21",
    evaluation_total_tokens: null,
    evaluation_cost_usd: null,
    cost_unknown_reason: null,
  },
  counts: {
    tasks: 3,
    sources: 3,
    claims: 2,
    evidence: 2,
    contradictions: 0,
    snapshots: 2,
    consumed_sources: 3,
    consumed_tool_calls: 4,
  },
  completed_phases: ["plan", "research"],
  phase_timings: { plan: "8" },
  report: {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    title: "NMC vs LFP",
    body_markdown: "# NMC vs LFP\n\nLFP is more thermally stable.\n",
    created_at: "2026-08-21T10:03:00.000Z",
  },
  tasks: [
    {
      id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
      task_key: "q1",
      objective: "Compare energy density",
      status: "completed",
      depends_on: [],
      allowed_tools: ["web_search"],
      worker_id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
      index: 1,
      display_name: "W01 · Compare energy density",
      started_at: "2026-08-21T10:00:20.000Z",
      completed_at: "2026-08-21T10:01:00.000Z",
      retries: 0,
    },
    {
      id: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
      task_key: "q2",
      objective: "Compare thermal stability",
      status: "running",
      depends_on: [],
      allowed_tools: ["web_search"],
      worker_id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee",
      index: 2,
      display_name: "W02 · Compare thermal stability",
      started_at: "2026-08-21T10:01:10.000Z",
      completed_at: null,
      retries: 0,
    },
    {
      id: "88888888-8888-4888-8888-888888888888",
      task_key: "q3",
      objective: "Compare lifecycle cost",
      status: "pending",
      depends_on: ["q1"],
      allowed_tools: ["web_search"],
      worker_id: "77777777-7777-4777-8777-777777777777",
      index: 3,
      display_name: "W03 · Compare lifecycle cost",
      started_at: null,
      completed_at: null,
      retries: 0,
    },
  ],
  workers: [
    {
      index: 1,
      display_name: "W01 · Compare energy density",
      worker_id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
      task_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
      task_key: "q1",
      role: "research_worker",
      agent_backed: false,
      parent: "Research Orchestrator",
      assigned_task: "Compare energy density",
      state: "completed",
      started_at: "2026-08-21T10:00:20.000Z",
      completed_at: "2026-08-21T10:01:00.000Z",
      allowed_tools: ["web_search"],
      retries: 0,
      skills: ["citation-audit"],
    },
    {
      index: 2,
      display_name: "W02 · Compare thermal stability",
      worker_id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee",
      task_id: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
      task_key: "q2",
      role: "research_worker",
      agent_backed: false,
      parent: "Research Orchestrator",
      assigned_task: "Compare thermal stability",
      state: "running",
      started_at: "2026-08-21T10:01:10.000Z",
      completed_at: null,
      allowed_tools: ["web_search"],
      retries: 0,
    },
    {
      index: 3,
      display_name: "W03 · Compare lifecycle cost",
      worker_id: "77777777-7777-4777-8777-777777777777",
      task_id: "88888888-8888-4888-8888-888888888888",
      task_key: "q3",
      role: "research_worker",
      agent_backed: false,
      parent: "Research Orchestrator",
      assigned_task: "Compare lifecycle cost",
      state: "ready",
      started_at: null,
      completed_at: null,
      allowed_tools: ["web_search"],
      retries: 0,
    },
  ],
  sources: [
    {
      id: "ffffffff-ffff-4fff-8fff-ffffffffffff",
      title: "Battery chemistry overview",
      url: "https://example.com/battery",
      domain: "example.com",
      source_type: "web",
      created_at: "2026-08-21T10:01:00.000Z",
      fetch_state: "fetched",
      snapshot_available: true,
      snapshot_id: "99999999-9999-4999-8999-999999999999",
      claim_count: 1,
      evidence_count: 1,
      task_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
      task_key: "q1",
      worker_index: 1,
    },
  ],
  snapshots: [
    {
      id: "99999999-9999-4999-8999-999999999999",
      source_id: "ffffffff-ffff-4fff-8fff-ffffffffffff",
      source_title: "Battery chemistry overview",
      url: "https://example.com/battery",
      retrieved_at: "2026-08-21T10:01:05.000Z",
      mime_type: "text/html",
      byte_size: 1200,
      content_hash: "abc123",
      word_count: 80,
      evidence_count: 1,
    },
  ],
  claims: [
    {
      id: "12121212-1212-4121-8121-121212121212",
      statement: "LFP is more thermally stable than NMC.",
      verification_status: "supported",
      source_id: "ffffffff-ffff-4fff-8fff-ffffffffffff",
      task_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
      task_key: "q1",
      worker_index: 1,
      evidence_count: 1,
      independent_source_count: 1,
      created_at: "2026-08-21T10:01:20.000Z",
    },
  ],
  evidence: [
    {
      id: "13131313-1313-4131-8131-131313131313",
      claim_id: "12121212-1212-4121-8121-121212121212",
      quote: "LFP generally exhibits better thermal stability.",
      locator: "p1",
      snapshot_id: "99999999-9999-4999-8999-999999999999",
      source_id: "ffffffff-ffff-4fff-8fff-ffffffffffff",
      created_at: "2026-08-21T10:01:20.000Z",
    },
  ],
  contradictions: [],
  activity: [
    { sequence: 1, type: "phase.completed", payload: { phase: "plan" }, created_at: "2026-08-21T10:00:30.000Z" },
    { sequence: 2, type: "worker.started", payload: { worker: "W01" }, created_at: "2026-08-21T10:00:40.000Z" },
    { sequence: 3, type: "tool.web_search", payload: { query: "NMC energy density" }, created_at: "2026-08-21T10:00:55.000Z" },
    { sequence: 4, type: "worker.completed", payload: { worker: "W01" }, created_at: "2026-08-21T10:01:05.000Z" },
    { sequence: 5, type: "worker.started", payload: { worker: "W02" }, created_at: "2026-08-21T10:01:15.000Z" },
  ],
  evaluations: [
    {
      evaluator_id: "claim_has_evidence",
      version: "1",
      category: "grounding",
      method: "deterministic_code",
      applicability: "active_now",
      description: "Claims have evidence",
      status: "passed",
      value: true,
    },
  ],
  resume: {
    domain_authority: "postgres",
    checkpoint_role: "worker_execution",
    completed_task_count: 1,
    remaining_task_count: 1,
    preserved_sources: 2,
    preserved_evidence: 1,
    current_phase: "research",
    latest_job_type: "execute_run",
    latest_job_status: "running",
    resumable: true,
  },
  architecture: {
    orchestrator: { label: "Research Orchestrator", kind: "deterministic" },
    planner: { label: "Planner Agent", kind: "llm_agent" },
    workers: { label: "Research Workers", kind: "langgraph_search" },
    extraction: { label: "Extraction Engine", kind: "deterministic" },
    verification: { label: "Verification Engine", kind: "deterministic" },
    quality: { label: "Quality Critic", kind: "deterministic" },
    synthesis: { label: "Synthesis Agent", kind: "llm_agent" },
    report: { label: "Report Engine", kind: "llm_agent" },
  },
};

export const settingsFixture = {
  identity: { label: "Local workspace", role: "Operator", plan: null, mode: "local" },
  providers: { google: { configured: true, model: "gemini-3.7-flash" }, tavily: { configured: true } },
  langsmith: { connected: true, project: "deepscout-dev", region: "EU", tracing: true },
  research_defaults: {
    max_iterations: 3,
    max_sources: 20,
    max_tool_calls: 40,
    durable_checkpoint: true,
    concurrency_note: "Worker fan-out is bounded by run concurrency_limit (default 3).",
  },
  health: { api: "ok", postgres: "ok", vector_store: "not_in_scope", langsmith: "connected" },
  security: { untrusted_content: "rendered as text", ssrf: "Private, loopback, link-local, CGNAT, and metadata URLs are blocked. Fetch pins TCP connect to the resolved IP." },
};
